local equipment = require('src/items/equipment.lua')
local stats = require('src/stats.lua')

local RARITY = {
    COMMON = {
        color = '|cffffffff',
        text = 'Common',
        priority = 0,
    },
    UNCOMMON = {
        color = '|cff2cfc03',
        text = 'Uncommon',
        priority = 1,
    },
    RARE = {
        color = '|cff036ffc',
        text = 'Rare',
        priority = 2,
    },
    EPIC = {
        color = '|cff8403fc',
        text = 'Epic',
        priority = 3,
    },
    LEGENDARY = {
        color = '|cffc4ab1a',
        text = 'Legendary',
        priority = 4,
    },
    DIVINE = {
        color = '|cff16c48d',
        text = 'Divine',
        priority = 5,
    },
}

local TYPE = {
    EQUIPMENT = 'equipment',
    CONSUMABLE = 'consumable',
}

    local ITEMS = {
[1] = {
    type = TYPE.EQUIPMENT,
    name = "Old boot",
    icon = "ReplaceableTextures\\CommandButtons\\BTNBoots.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    slot = equipment.SLOT.FEET,
    stackSize = 1,
    cost = 30,
    usableClasses = {FourCC('Hyuj'),FourCC('Hazr')},
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 10,
            tickrate = 5,
        },
    },
},
[2] = {
    type = TYPE.EQUIPMENT,
    name = "Rusty Ring",
    icon = "ReplaceableTextures\\CommandButtons\\BTNGoldRing.blp",
    itemLevel = 5,
    requiredLevel = 5,
    rarity = RARITY.UNCOMMON,
    slot = equipment.SLOT.RING,
    stackSize = 1,
    cost = 150,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 10,
            tickrate = 5,
        },
    },
},
[3] = {
    type = TYPE.EQUIPMENT,
    name = "Iron Helmet",
    icon = "ReplaceableTextures\\CommandButtons\\BTNHelmutPurple.blp",
    itemLevel = 3,
    requiredLevel = 3,
    rarity = RARITY.UNCOMMON,
    slot = equipment.SLOT.HELMET,
    stackSize = 1,
    cost = 80,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 40,
            tickrate = 5,
        },
    },
},
[4] = {
    type = TYPE.EQUIPMENT,
    name = "Copper Dagger",
    icon = "ReplaceableTextures\\CommandButtons\\BTNDaggerOfEscape.blp",
    itemLevel = 20,
    requiredLevel = 10,
    rarity = RARITY.RARE,
    slot = equipment.SLOT.WEAPON,
    stackSize = 1,
    cost = 300,
    stats = {
    },
},
[5] = {
    type = TYPE.CONSUMABLE,
    name = "Health Potion",
    icon = "ReplaceableTextures\\CommandButtons\\BTNPotionGreen.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    stackSize = 5,
    text = "Heal yourself for 200 HP.",
    spell = "healpot1",
    cost = 20,
    stats = {
    },
},
[6] = {
    type = TYPE.CONSUMABLE,
    name = "Cheese",
    icon = "ReplaceableTextures\\CommandButtons\\BTNCheese.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    stackSize = 20,
    text = "Eat to heal 60 HP per 3 seconds.|nMust be out of combat.",
    spell = "food1",
    cost = 5,
    stats = {
    },
},
[7] = {
    type = TYPE.EQUIPMENT,
    name = "Chain Vest",
    icon = "ReplaceableTextures\\CommandButtons\\BTNMantleOfIntelligence.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    slot = equipment.SLOT.CHEST,
    stackSize = 1,
    cost = 35,
    stats = {
    },
},
[8] = {
    type = TYPE.EQUIPMENT,
    name = "Cloak",
    icon = "ReplaceableTextures\\CommandButtons\\BTNCloak.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    slot = equipment.SLOT.BACK,
    stackSize = 1,
    cost = 35,
    stats = {
        {
            type = stats.PERCENT_MOVE_SPEED,
            amount = 1.01,
            tickrate = 5,
        },
    },
},
[9] = {
    type = TYPE.CONSUMABLE,
    name = "River Turtle Meat",
    icon = "ReplaceableTextures\\CommandButtons\\BTNMonsterLure.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    stackSize = 10,
    text = "The meat of a turtle...|nI think Fred wants this.",
    cost = 20,
    stats = {
    },
},
[10] = {
    type = TYPE.EQUIPMENT,
    name = "Wolf Helmet",
    icon = "war3mapImported\\BTNWolf.blp",
    slot = equipment.SLOT.HELMET,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 15,
            tickrate = 5,
        },
    },
},
[11] = {
    type = TYPE.EQUIPMENT,
    name = "Giant Wolf Helmet",
    icon = "war3mapImported\\BTNCompanionWolfDire.blp",
    slot = equipment.SLOT.HELMET,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 25,
            tickrate = 5,
        },
    },
},
[12] = {
    type = TYPE.EQUIPMENT,
    name = "Leather Helmet",
    icon = "war3mapImported\\BTNHelmet.blp",
    slot = equipment.SLOT.HELMET,
    requiredLevel = 19,
    itemLevel = 32,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 60,
            tickrate = 5,
        },
    },
},
[13] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Helmet",
    icon = "war3mapImported\\BTNWater Battle Helmet.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.HELMET,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 45,
            tickrate = 5,
        },
    },
},
[14] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Hood",
    icon = "war3mapImported\\BTNINV_Helmet_17.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.HELMET,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 35,
            tickrate = 5,
        },
    },
},
[15] = {
    type = TYPE.EQUIPMENT,
    name = "Iron Helmet",
    icon = "war3mapImported\\BTNAllianceHelmet.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.HELMET,
    requiredLevel = 14,
    itemLevel = 24,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 6,
            tickrate = 5,
        },
        {
            type = stats.RAW_HIT_POINTS,
            amount = 70,
            tickrate = 5,
        },
    },
},
[16] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Mask",
    icon = "war3mapImported\\BTNTiki Mask B.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.HELMET,
    requiredLevel = 14,
    itemLevel = 24,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 8,
            tickrate = 5,
        },
        {
            type = stats.RAW_HIT_POINTS,
            amount = 55,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 8,
            tickrate = 5,
        },
    },
},
[17] = {
    type = TYPE.EQUIPMENT,
    name = "Yeti Skull Helm",
    icon = "war3mapImported\\BTNNecroHelm.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.HELMET,
    requiredLevel = 16,
    itemLevel = 27,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 80,
            tickrate = 5,
        },
        {
            type = stats.RAW_INCOMING_DAMAGE,
            amount = -5,
            tickrate = 5,
        },
        {
            type = stats.HEALTH_REGEN,
            amount = 3,
            tickrate = 5,
        },
    },
},
[18] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Pendant",
    icon = "war3mapImported\\BTNEmpty Amulet.blp",
    slot = equipment.SLOT.NECK,
    requiredLevel = 15,
    itemLevel = 26,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_INCOMING_HEALING,
            amount = 5,
            tickrate = 5,
        },
    },
},
[19] = {
    type = TYPE.EQUIPMENT,
    name = "Warlord's Necklace",
    icon = "war3mapImported\\BTNNecklaceOfWarrior.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.NECK,
    requiredLevel = 17,
    itemLevel = 36,
    rarity = RARITY.RARE,
    cost = 0,
    stats = {
        {
            type = stats.RAW_INCOMING_HEALING,
            amount = 7,
            tickrate = 5,
        },
    },
},
[20] = {
    type = TYPE.EQUIPMENT,
    name = "Shell Pads",
    icon = "war3mapImported\\BTNDemonShoulderUPG1.blp",
    slot = equipment.SLOT.SHOULDERS,
    requiredLevel = 6,
    itemLevel = 10,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 20,
            tickrate = 5,
        },
    },
},
[21] = {
    type = TYPE.EQUIPMENT,
    name = "Cultist Epaulets",
    icon = "war3mapImported\\BTNShoulderplate.blp",
    slot = equipment.SLOT.SHOULDERS,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 60,
            tickrate = 5,
        },
    },
},
[22] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Caster Pads",
    icon = "",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.SHOULDERS,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 35,
            tickrate = 5,
        },
    },
},
[23] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Warrior Spaulders",
    icon = "",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.SHOULDERS,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 45,
            tickrate = 5,
        },
    },
},
[24] = {
    type = TYPE.EQUIPMENT,
    name = "Warlord's Shoulders",
    icon = "",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.SHOULDERS,
    requiredLevel = 17,
    itemLevel = 29,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 8,
            tickrate = 5,
        },
        {
            type = stats.RAW_HIT_POINTS,
            amount = 70,
            tickrate = 5,
        },
    },
},
[25] = {
    type = TYPE.EQUIPMENT,
    name = "Turtle Leather Vest",
    icon = "war3mapImported\\BTNINV_Chest_Leather_02.blp",
    slot = equipment.SLOT.CHEST,
    requiredLevel = 2,
    itemLevel = 4,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 20,
            tickrate = 5,
        },
    },
},
[26] = {
    type = TYPE.EQUIPMENT,
    name = "Cultist Robes",
    icon = "war3mapImported\\BTNINV_Robe_03.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.CHEST,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 80,
            tickrate = 5,
        },
    },
},
[27] = {
    type = TYPE.EQUIPMENT,
    name = "Cultist Cuirass",
    icon = "war3mapImported\\BTNPlateArmor.blp",
    usableClasses = {FourCC('Htar'),FourCC('Hyuj')},
    slot = equipment.SLOT.CHEST,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 115,
            tickrate = 5,
        },
    },
},
[28] = {
    type = TYPE.EQUIPMENT,
    name = "Hardened Turtle Carapace",
    icon = "",
    slot = equipment.SLOT.CHEST,
    requiredLevel = 6,
    itemLevel = 10,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 45,
            tickrate = 5,
        },
    },
},
[29] = {
    type = TYPE.EQUIPMENT,
    name = "Mammoth Fur Vest",
    icon = "",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.CHEST,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 70,
            tickrate = 5,
        },
    },
},
[30] = {
    type = TYPE.EQUIPMENT,
    name = "Mammoth Fur Robe",
    icon = "",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.CHEST,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 65,
            tickrate = 5,
        },
    },
},
[31] = {
    type = TYPE.EQUIPMENT,
    name = "Yeti Robe",
    icon = "",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.CHEST,
    requiredLevel = 16,
    itemLevel = 27,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 85,
            tickrate = 5,
        },
    },
},
[32] = {
    type = TYPE.EQUIPMENT,
    name = "Wolf Pelt",
    icon = "war3mapImported\\BTNINV_Misc_Cape_04.blp",
    slot = equipment.SLOT.BACK,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 10,
            tickrate = 5,
        },
    },
},
[33] = {
    type = TYPE.EQUIPMENT,
    name = "Worn Cape",
    icon = "war3mapImported\\BTNINV_Misc_Cape_14.blp",
    slot = equipment.SLOT.BACK,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 45,
            tickrate = 5,
        },
    },
},
[34] = {
    type = TYPE.EQUIPMENT,
    name = "Mammoth Fur-Lined Cape",
    icon = "war3mapImported\\BTNcloak1.blp",
    slot = equipment.SLOT.BACK,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 20,
            tickrate = 5,
        },
    },
},
[35] = {
    type = TYPE.EQUIPMENT,
    name = "Priest's Cloak",
    icon = "",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.BACK,
    requiredLevel = 16,
    itemLevel = 27,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 12,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 12,
            tickrate = 5,
        },
    },
},
[36] = {
    type = TYPE.EQUIPMENT,
    name = "Fur-Lined Pants",
    icon = "war3mapImported\\BTNINV_Pants_Wolf.blp",
    slot = equipment.SLOT.LEGS,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 10,
            tickrate = 5,
        },
    },
},
[37] = {
    type = TYPE.EQUIPMENT,
    name = "Spiritual Wolf Leggings",
    icon = "war3mapImported\\BTNINV_Pants_02.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.LEGS,
    requiredLevel = 12,
    itemLevel = 21,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 10,
            tickrate = 5,
        },
        {
            type = stats.RAW_HIT_POINTS,
            amount = 30,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 10,
            tickrate = 5,
        },
    },
},
[38] = {
    type = TYPE.EQUIPMENT,
    name = "Cultist Trousers",
    icon = "war3mapImported\\BTNpants01.blp",
    slot = equipment.SLOT.LEGS,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
    },
},
[39] = {
    type = TYPE.EQUIPMENT,
    name = "Mammoth Hide Leggings",
    icon = "war3mapImported\\BTNLeatherPants4.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.LEGS,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 10,
            tickrate = 5,
        },
    },
},
[40] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Plate Leggings",
    icon = "",
    slot = equipment.SLOT.LEGS,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 50,
            tickrate = 5,
        },
    },
},
[41] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Cloth Leggings",
    icon = "",
    slot = equipment.SLOT.LEGS,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 50,
            tickrate = 5,
        },
    },
},
[42] = {
    type = TYPE.EQUIPMENT,
    name = "Old Boots",
    icon = "war3mapImported\\BTNINV_Boots_09.blp",
    slot = equipment.SLOT.FEET,
    requiredLevel = 1,
    itemLevel = 3,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_MOVE_SPEED,
            amount = 1.01,
            tickrate = 5,
        },
        {
            type = stats.HEALTH_REGEN,
            amount = 2,
            tickrate = 5,
        },
    },
},
[43] = {
    type = TYPE.EQUIPMENT,
    name = "Worn Running Boots",
    icon = "war3mapImported\\BTNINV_Boots_07.blp",
    slot = equipment.SLOT.FEET,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_MOVE_SPEED,
            amount = 1.01,
            tickrate = 5,
        },
        {
            type = stats.HEALTH_REGEN,
            amount = 4,
            tickrate = 5,
        },
    },
},
[44] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Sabatons",
    icon = "war3mapImported\\BTNINV_Boots_Plate_08.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.FEET,
    requiredLevel = 15,
    itemLevel = 26,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_MOVE_SPEED,
            amount = 1.03,
            tickrate = 5,
        },
        {
            type = stats.HEALTH_REGEN,
            amount = 5,
            tickrate = 5,
        },
    },
},
[45] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Kickers",
    icon = "war3mapImported\\BTNHeavyBoots.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.FEET,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_MOVE_SPEED,
            amount = 1.02,
            tickrate = 5,
        },
        {
            type = stats.HEALTH_REGEN,
            amount = 2,
            tickrate = 5,
        },
    },
},
[46] = {
    type = TYPE.EQUIPMENT,
    name = "Mammoth Skin Boots",
    icon = "war3mapImported\\BTNINV_Boots_08.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.FEET,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_MOVE_SPEED,
            amount = 1.02,
            tickrate = 5,
        },
        {
            type = stats.HEALTH_REGEN,
            amount = 2,
            tickrate = 5,
        },
    },
},
[47] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Slippers",
    icon = "war3mapImported\\BTN.Boots3.BLP",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.FEET,
    requiredLevel = 15,
    itemLevel = 26,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_MOVE_SPEED,
            amount = 1.03,
            tickrate = 5,
        },
        {
            type = stats.HEALTH_REGEN,
            amount = 7,
            tickrate = 5,
        },
    },
},
[48] = {
    type = TYPE.EQUIPMENT,
    name = "Warlord's Boots",
    icon = "war3mapImported\\BTNBlizzard_Boots.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.FEET,
    requiredLevel = 17,
    itemLevel = 29,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_MOVE_SPEED,
            amount = 1.05,
            tickrate = 5,
        },
        {
            type = stats.HEALTH_REGEN,
            amount = 10,
            tickrate = 5,
        },
    },
},
[49] = {
    type = TYPE.EQUIPMENT,
    name = "Fur-lined Gloves",
    icon = "war3mapImported\\BTNFur Gauntlet.blp",
    slot = equipment.SLOT.HANDS,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 8,
            tickrate = 5,
        },
    },
},
[50] = {
    type = TYPE.EQUIPMENT,
    name = "Leather Gloves",
    icon = "war3mapImported\\BTNLeather Gauntlet.blp",
    slot = equipment.SLOT.HANDS,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 16,
            tickrate = 5,
        },
    },
},
[51] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Handguards",
    icon = "",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.HANDS,
    requiredLevel = 12,
    itemLevel = 21,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 4,
            tickrate = 5,
        },
        {
            type = stats.RAW_HIT_POINTS,
            amount = 26,
            tickrate = 5,
        },
        {
            type = stats.RAW_INCOMING_DAMAGE,
            amount = -1,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 4,
            tickrate = 5,
        },
    },
},
[52] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Handwraps",
    icon = "war3mapImported\\BTNTroll_VooDoo_Gloves.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.HANDS,
    requiredLevel = 12,
    itemLevel = 19,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 20,
            tickrate = 5,
        },
    },
},
[53] = {
    type = TYPE.EQUIPMENT,
    name = "High Priest's Gloves",
    icon = "war3mapImported\\BTNMana gloves.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.HANDS,
    requiredLevel = 16,
    itemLevel = 27,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 8,
            tickrate = 5,
        },
        {
            type = stats.RAW_HIT_POINTS,
            amount = 25,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 8,
            tickrate = 5,
        },
    },
},
[54] = {
    type = TYPE.EQUIPMENT,
    name = "Brass Ring",
    icon = "war3mapImported\\BTNINV_Jewelry_Ring_13.blp",
    slot = equipment.SLOT.RING,
    requiredLevel = 19,
    itemLevel = 32,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_DAMAGE,
            amount = 1.02,
            tickrate = 5,
        },
        {
            type = stats.PERCENT_SPELL_DAMAGE,
            amount = 1.02,
            tickrate = 5,
        },
        {
            type = stats.PERCENT_HEALING,
            amount = 1.02,
            tickrate = 5,
        },
    },
},
[55] = {
    type = TYPE.EQUIPMENT,
    name = "Warlord's Ring",
    icon = "war3mapImported\\BTNring1.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.RING,
    requiredLevel = 17,
    itemLevel = 36,
    rarity = RARITY.RARE,
    cost = 0,
    stats = {
        {
            type = stats.PERCENT_DAMAGE,
            amount = 1.04,
            tickrate = 5,
        },
    },
},
[56] = {
    type = TYPE.EQUIPMENT,
    name = "Turtle Claw",
    icon = "war3mapImported\\BTNDagger.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 2,
    itemLevel = 4,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 3,
            tickrate = 5,
        },
    },
},
[57] = {
    type = TYPE.EQUIPMENT,
    name = "Giant Wolf Fang",
    icon = "war3mapImported\\BTNBoneDagger.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 6,
            tickrate = 5,
        },
    },
},
[58] = {
    type = TYPE.EQUIPMENT,
    name = "Cultist Wand",
    icon = "war3mapImported\\BTNMurgulStaff.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 12,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 12,
            tickrate = 5,
        },
    },
},
[59] = {
    type = TYPE.EQUIPMENT,
    name = "Chieftan's Sword",
    icon = "war3mapImported\\BTNCeremonial Sword.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 14,
    itemLevel = 24,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 13,
            tickrate = 5,
        },
    },
},
[60] = {
    type = TYPE.EQUIPMENT,
    name = "Warlord's Bloody Axe",
    icon = "war3mapImported\\BTNBloodyAxe.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 17,
    itemLevel = 29,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 17,
            tickrate = 5,
        },
    },
},
[61] = {
    type = TYPE.EQUIPMENT,
    name = "Warlord's Mageblade",
    icon = "war3mapImported\\BTNWKnightBlade.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 17,
    itemLevel = 29,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 20,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 20,
            tickrate = 5,
        },
    },
},
[62] = {
    type = TYPE.EQUIPMENT,
    name = "Spiked Bone Club",
    icon = "war3mapImported\\BTNSpikedClub.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 7,
    itemLevel = 12,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 8,
            tickrate = 5,
        },
    },
},
[63] = {
    type = TYPE.EQUIPMENT,
    name = "Giant Bone Club",
    icon = "war3mapImported\\BTNPrehistoric Dino Club.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 12,
    itemLevel = 21,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 15,
            tickrate = 5,
        },
    },
},
[64] = {
    type = TYPE.EQUIPMENT,
    name = "Broadsword",
    icon = "war3mapImported\\BTNAncientRelic.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
    },
},
[65] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Battle Axe",
    icon = "war3mapImported\\BTNMysticHatchet.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 14,
    itemLevel = 22,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 25,
            tickrate = 5,
        },
    },
},
[66] = {
    type = TYPE.EQUIPMENT,
    name = "Troll Staff",
    icon = "war3mapImported\\BTNWandOfCosmicEnergy.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 14,
    itemLevel = 22,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 20,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 20,
            tickrate = 5,
        },
    },
},
[67] = {
    type = TYPE.EQUIPMENT,
    name = "High Priest's Staff",
    icon = "war3mapImported\\BTN_God_Scepter.blp",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 16,
    itemLevel = 27,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 35,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 35,
            tickrate = 5,
        },
    },
},
[68] = {
    type = TYPE.EQUIPMENT,
    name = "Yeti Horn",
    icon = "war3mapImported\\BTNHorn.blp",
    usableClasses = {FourCC('Hyuj'),FourCC('Htar'),FourCC('Hstm')},
    slot = equipment.SLOT.WEAPON,
    requiredLevel = 16,
    itemLevel = 27,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_DAMAGE,
            amount = 35,
            tickrate = 5,
        },
    },
},
[69] = {
    type = TYPE.EQUIPMENT,
    name = "Shell Shield",
    icon = "war3mapImported\\BTNNerubianShield.blp",
    usableClasses = {FourCC('Htar')},
    slot = equipment.SLOT.OFFHAND,
    requiredLevel = 1,
    itemLevel = 3,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 5,
            tickrate = 5,
        },
        {
            type = stats.RAW_INCOMING_DAMAGE,
            amount = -2,
            tickrate = 5,
        },
    },
},
[70] = {
    type = TYPE.EQUIPMENT,
    name = "Cultist Blocker",
    icon = "war3mapImported\\BTNbuckler1.blp",
    usableClasses = {FourCC('Htar')},
    slot = equipment.SLOT.OFFHAND,
    requiredLevel = 16,
    itemLevel = 25,
    rarity = RARITY.COMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 32,
            tickrate = 5,
        },
        {
            type = stats.RAW_INCOMING_DAMAGE,
            amount = -6,
            tickrate = 5,
        },
    },
},
[71] = {
    type = TYPE.EQUIPMENT,
    name = "Chieftan's Shield",
    icon = "war3mapImported\\BTNTowerShieldv.1.2.blp",
    usableClasses = {FourCC('Htar')},
    slot = equipment.SLOT.OFFHAND,
    requiredLevel = 14,
    itemLevel = 24,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 20,
            tickrate = 5,
        },
        {
            type = stats.RAW_INCOMING_DAMAGE,
            amount = -5,
            tickrate = 5,
        },
    },
},
[72] = {
    type = TYPE.EQUIPMENT,
    name = "High Priest's Tome",
    icon = "war3mapImported\\BTNSimpleBook1.BLP",
    usableClasses = {FourCC('Hazr'),FourCC('Hivn')},
    slot = equipment.SLOT.OFFHAND,
    requiredLevel = 16,
    itemLevel = 27,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_SPELL_DAMAGE,
            amount = 15,
            tickrate = 5,
        },
        {
            type = stats.RAW_HIT_POINTS,
            amount = 20,
            tickrate = 5,
        },
        {
            type = stats.RAW_HEALING,
            amount = 15,
            tickrate = 5,
        },
    },
},
[73] = {
    type = TYPE.EQUIPMENT,
    name = "Yeti Bone Shield",
    icon = "",
    usableClasses = {FourCC('Htar')},
    slot = equipment.SLOT.OFFHAND,
    requiredLevel = 16,
    itemLevel = 27,
    rarity = RARITY.UNCOMMON,
    cost = 0,
    stats = {
        {
            type = stats.RAW_HIT_POINTS,
            amount = 45,
            tickrate = 5,
        },
        {
            type = stats.RAW_INCOMING_DAMAGE,
            amount = -10,
            tickrate = 5,
        },
    },
},
[74] = {
    type = TYPE.CONSUMABLE,
    name = "Return Stone Test",
    icon = "ReplaceableTextures\\CommandButtons\\BTNPhilosophersStone.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    stackSize = 1,
    text = "Return to town.|nMust be out of combat.",
    spell = "hearthstone",
    cost = -1,
    stats = {
    },
},
[75] = {
    type = TYPE.CONSUMABLE,
    name = "Spirit Winds",
    icon = "ReplaceableTextures\\CommandButtons\\BTNWindWalkOn.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    stackSize = 1,
    text = "Engage the spirit winds to travel faster.|nMust be out of combat.",
    spell = "mount",
    cost = -1,
    stats = {
    },
},
[76] = {
    type = TYPE.CONSUMABLE,
    name = "Mammoth Fur",
    icon = "ReplaceableTextures\\CommandButtons\\BTNRedDragon.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    stackSize = 10,
    text = "The fur of a Mammoth...|nSure looks warm.",
    cost = 20,
    stats = {
    },
},
[77] = {
    type = TYPE.CONSUMABLE,
    name = "Giant Mammoth Fur",
    icon = "ReplaceableTextures\\CommandButtons\\BTNRobeOfTheMagi.blp",
    itemLevel = 1,
    requiredLevel = 1,
    rarity = RARITY.COMMON,
    stackSize = 10,
    text = "This looks...warmer.",
    cost = 20,
    stats = {
    },
},
}
 return {ITEMS=ITEMS, TYPE=TYPE}
