-- UI Constants

local BACKPACK_ITEM_SIZE = 0.025

return {
    ACTION_ITEM_SIZE = 0.04,
    CAST_BAR_WIDTH = 0.16,
    CAST_BAR_HEIGHT = 0.02,
    BAR_WIDTH = 0.19,
    BAR_HEIGHT = 0.01,
    BUFF_ICON_SIZE = 0.02,
    BACKPACK_ITEM_SIZE = BACKPACK_ITEM_SIZE,
    BACKPACK_SIZE = BACKPACK_ITEM_SIZE * 6 + 0.06,
    EQUIPMENT_ITEM_SIZE = 0.03,
    EXP_BAR_WIDTH = 0.50,
    EXP_BAR_HEIGHT = 0.01,
    DIALOG_WIDTH = 0.4,
    DIALOG_HEIGHT = 0.4,
    QUEST_LOG_WIDTH = 0.2,
    QUEST_LOG_HEIGHT = 0.4,
}
