-- UI Constants

local BACKPACK_ITEM_SIZE = 0.025

return {
    ACTION_ITEM_SIZE = 0.04,
    CAST_BAR_WIDTH = 0.16,
    CAST_BAR_HEIGHT = 0.02,
    BAR_WIDTH = 0.20,
    BAR_HEIGHT = 0.01,
    BUFF_ICON_SIZE = 0.02,
    BACKPACK_ITEM_SIZE = BACKPACK_ITEM_SIZE,
    BACKPACK_SIZE = BACKPACK_ITEM_SIZE * 6,
}
