-- UI Constants

local BACKPACK_ITEM_SIZE = 0.025

return {
    ACTION_ITEM_SIZE = 0.045,
    ITEM_ITEM_SIZE = 0.03,
    CAST_BAR_WIDTH = 0.16,
    CAST_BAR_HEIGHT = 0.028,
    BAR_WIDTH = 0.19,
    BAR_HEIGHT = 0.01,
    BUFF_ICON_SIZE = 0.02,
    BACKPACK_ITEM_SIZE = BACKPACK_ITEM_SIZE,
    BACKPACK_SIZE = BACKPACK_ITEM_SIZE * 6 + 0.06,
    EQUIPMENT_ITEM_SIZE = 0.03,
    EXP_BAR_WIDTH = 0.2475,
    EXP_BAR_HEIGHT = 0.01,
    DIALOG_WIDTH = 0.4,
    DIALOG_HEIGHT = 0.4,
    VENDOR_WIDTH = 0.2,
    VENDOR_HEIGHT = 0.3,
    QUEST_LOG_WIDTH = 0.2,
    QUEST_LOG_HEIGHT = 0.4,
    MENU_BUTTON_SIZE = 0.03,
    STATS_WIDTH = 0.12,
    STATS_HEIGHT = 0.16,
    TALENTS_WIDTH = 0.2,
    TALENTS_HEIGHT = 0.3,
    TALENT_ICON_SIZE = 0.03,
    LOOT_ROLL_WIDTH = 0.24,
    LOOT_ROLL_HEIGHT = 0.08,
}
