gg_rct_ironwellenter1 = nil
gg_rct_freydellenter1 = nil
gg_rct_rain1 = nil
gg_rct_rain2 = nil
gg_rct_rain3 = nil
gg_rct_iceenter1 = nil
gg_rct_wolvesenter1 = nil
gg_rct_wolvesenter2 = nil
gg_rct_forestenter1 = nil
gg_rct_forestenter2 = nil
gg_cam_Camera_001 = nil
gg_trg_Untitled_Trigger_001 = nil
gg_unit_nvil_0069 = nil
gg_unit_nvl2_0070 = nil
gg_unit_nvil_0071 = nil
gg_unit_nemi_0014 = nil
function InitGlobals()
end

local REPLACE_ME
function CreateUnitsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("nitw"), -15718.7, -3380.4, 152.528, FourCC("nitw"))
end

function CreateNeutralHostile()
    local p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1050.5, -2679.1, 260.960, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2239.2, -2118.5, 268.438, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -819.9, -768.3, 266.823, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -648.4, -1042.3, 246.699, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2908.1, -631.9, 293.398, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2665.0, -311.7, 323.682, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1533.1, -750.1, 238.219, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1707.7, -770.7, 256.650, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1777.5, 210.9, 250.859, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1366.4, 283.1, 340.058, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2273.2, 207.4, 266.659, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1910.1, -1655.7, 44.345, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1290.0, -1429.9, 262.992, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -983.0, -3816.5, 151.746, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1676.5, -3934.1, 142.831, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2955.1, -3566.7, 238.114, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -3305.2, -3308.9, 119.469, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -3612.6, -2246.7, 317.866, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -3414.3, -2012.5, 136.817, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -4370.8, -1378.0, 359.341, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2428.6, 2016.1, 282.057, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2208.2, 2057.0, 264.344, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -3605.8, 1642.5, 270.033, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -3870.1, 1510.7, 286.949, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1116.6, 1966.4, 266.457, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -813.2, 1858.7, 240.388, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2705.8, 576.5, 229.720, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -4631.9, 246.9, 312.477, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2492.1, -4991.6, 102.145, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -2619.4, -5506.5, 298.884, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1856.5, -5876.7, 45.622, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1273.9, -5753.2, 76.439, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -514.0, -4738.5, 209.438, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -758.0, -4195.1, 229.384, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmbs"), -1655.6, -4492.8, 245.494, FourCC("hmbs"))
    u = BlzCreateUnitWithSkin(p, FourCC("lold"), -5230.7, -4168.0, 328.059, FourCC("lold"))
    u = BlzCreateUnitWithSkin(p, FourCC("lold"), -5127.6, -5365.2, 43.486, FourCC("lold"))
    u = BlzCreateUnitWithSkin(p, FourCC("lold"), -5882.2, -6170.1, 18.305, FourCC("lold"))
    u = BlzCreateUnitWithSkin(p, FourCC("lold"), -4549.7, -5499.3, 48.944, FourCC("lold"))
    u = BlzCreateUnitWithSkin(p, FourCC("lold"), -5262.1, -7154.2, 16.266, FourCC("lold"))
    u = BlzCreateUnitWithSkin(p, FourCC("lold"), -6657.5, -5206.2, 341.249, FourCC("lold"))
    u = BlzCreateUnitWithSkin(p, FourCC("lold"), -6276.7, -4618.6, 342.905, FourCC("lold"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 1307.9, 1034.1, 285.991, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 1511.2, 1032.9, 250.413, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 1280.1, -772.2, 62.563, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 1523.6, -864.2, 82.482, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 2157.2, 345.2, 186.270, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 2276.3, 244.1, 177.218, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 2453.1, -218.9, 160.298, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 2025.5, -896.7, 122.405, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 3165.9, -1268.6, 176.356, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 3273.4, -1075.1, 192.321, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 3098.6, 687.3, 243.872, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 3320.7, 460.1, 241.147, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 4751.2, -1696.3, 130.534, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 4888.0, -1473.9, 144.734, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 3957.8, -18.4, 303.251, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 3829.9, -127.3, 315.479, FourCC("hwol"))
    u = BlzCreateUnitWithSkin(p, FourCC("hwol"), 1072.9, -31.9, 69.234, FourCC("hwol"))
end

function CreateNeutralPassive()
    local p = Player(PLAYER_NEUTRAL_PASSIVE)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("nvlw"), 2804.5, -4316.2, 159.208, FourCC("nvlw"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvlk"), 2386.1, -3037.9, 246.899, FourCC("nvlk"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvk2"), 2431.0, -3062.8, 206.967, FourCC("nvk2"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvlw"), 1512.6, -3050.4, 278.567, FourCC("nvlw"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvl2"), 1506.5, -3833.3, 308.094, FourCC("nvl2"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvil"), 1522.8, -3920.0, 39.473, FourCC("nvil"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvil"), 2881.8, -3889.8, 208.095, FourCC("nvil"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvl2"), 2375.6, -4005.7, 193.693, FourCC("nvl2"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvl2"), 1332.0, -2627.9, 208.850, FourCC("nvl2"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvil"), 1173.7, -2574.4, 291.118, FourCC("nvil"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvk2"), 2877.6, -2768.2, 49.653, FourCC("nvk2"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvlk"), 2862.8, -2630.5, 333.546, FourCC("nvlk"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvlw"), 3041.6, -2641.1, 205.458, FourCC("nvlw"))
    gg_unit_nemi_0014 = BlzCreateUnitWithSkin(p, FourCC("nemi"), 1380.5, -4077.3, 353.960, FourCC("nemi"))
    u = BlzCreateUnitWithSkin(p, FourCC("nbee"), 2550.7, -4365.4, 109.620, FourCC("nbee"))
    u = BlzCreateUnitWithSkin(p, FourCC("hrdh"), 3101.3, -2818.5, 316.620, FourCC("hrdh"))
    u = BlzCreateUnitWithSkin(p, FourCC("vl2w"), 16098.7, -13461.5, 261.384, FourCC("vl2w"))
    u = BlzCreateUnitWithSkin(p, FourCC("nviw"), 17113.8, -13518.8, 205.473, FourCC("nviw"))
    u = BlzCreateUnitWithSkin(p, FourCC("vlww"), 16239.8, -13837.2, 148.617, FourCC("vlww"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvlw"), 16715.4, -13484.0, 277.709, FourCC("nvlw"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvl2"), 16770.2, -13536.7, 183.205, FourCC("nvl2"))
    u = BlzCreateUnitWithSkin(p, FourCC("nalb"), 15429.5, -15090.6, 158.867, FourCC("nalb"))
    u = BlzCreateUnitWithSkin(p, FourCC("nalb"), 16236.0, -14525.1, 284.115, FourCC("nalb"))
    u = BlzCreateUnitWithSkin(p, FourCC("nalb"), 18091.7, -13148.4, 335.632, FourCC("nalb"))
    u = BlzCreateUnitWithSkin(p, FourCC("nalb"), 17645.9, -9597.7, 65.118, FourCC("nalb"))
    u = BlzCreateUnitWithSkin(p, FourCC("nalb"), 18826.4, -8565.1, 234.049, FourCC("nalb"))
    u = BlzCreateUnitWithSkin(p, FourCC("necr"), 17264.8, -8690.9, 5.735, FourCC("necr"))
    u = BlzCreateUnitWithSkin(p, FourCC("necr"), 18897.9, -9692.5, 251.155, FourCC("necr"))
    u = BlzCreateUnitWithSkin(p, FourCC("nrat"), 17187.8, -15815.3, 196.991, FourCC("nrat"))
    u = BlzCreateUnitWithSkin(p, FourCC("nrat"), 18117.1, -15856.7, 115.371, FourCC("nrat"))
    u = BlzCreateUnitWithSkin(p, FourCC("nrat"), 16306.0, -15905.8, 185.301, FourCC("nrat"))
    u = BlzCreateUnitWithSkin(p, FourCC("nrat"), 15233.7, -15875.8, 345.948, FourCC("nrat"))
    u = BlzCreateUnitWithSkin(p, FourCC("vlww"), 12438.7, -10049.2, 180.921, FourCC("vlww"))
    u = BlzCreateUnitWithSkin(p, FourCC("vl2w"), 12783.7, -10807.2, 235.499, FourCC("vl2w"))
    u = BlzCreateUnitWithSkin(p, FourCC("nviw"), 12467.2, -11859.0, 139.871, FourCC("nviw"))
    u = BlzCreateUnitWithSkin(p, FourCC("vlww"), 12468.2, -12867.1, 258.626, FourCC("vlww"))
    u = BlzCreateUnitWithSkin(p, FourCC("nviw"), 13226.2, -12982.0, 238.433, FourCC("nviw"))
    u = BlzCreateUnitWithSkin(p, FourCC("vl2w"), 14017.6, -12736.6, 351.101, FourCC("vl2w"))
    u = BlzCreateUnitWithSkin(p, FourCC("vlww"), 14145.1, -13005.4, 73.819, FourCC("vlww"))
    u = BlzCreateUnitWithSkin(p, FourCC("hrdh"), 15845.5, -12374.0, 357.560, FourCC("hrdh"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 17838.4, -11552.7, 168.584, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 17841.5, -11381.6, 172.687, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 17447.3, -10975.6, 266.894, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 17880.6, -10981.2, 268.134, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 12391.1, -9523.3, 91.319, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 12828.5, -9538.9, 93.046, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvil"), 16391.3, -13561.0, 67.604, FourCC("nvil"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvk2"), 16403.4, -13458.5, 237.328, FourCC("nvk2"))
    u = BlzCreateUnitWithSkin(p, FourCC("nvlk"), 16455.5, -13506.3, 188.627, FourCC("nvlk"))
    u = BlzCreateUnitWithSkin(p, FourCC("nhef"), 15062.4, -12857.7, 213.600, FourCC("nhef"))
    u = BlzCreateUnitWithSkin(p, FourCC("nhem"), 17001.4, -13337.5, 239.470, FourCC("nhem"))
    u = BlzCreateUnitWithSkin(p, FourCC("nhem"), 17094.3, -13791.3, 155.630, FourCC("nhem"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 3383.0, -3043.8, 359.463, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 3379.6, -3626.1, 354.915, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 2202.9, -4797.9, 268.801, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 1623.1, -4777.0, 274.996, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -381.7, -3037.1, 197.904, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -422.3, -3582.1, 161.730, FourCC("hfoo"))
    gg_unit_nvil_0069 = BlzCreateUnitWithSkin(p, FourCC("nvil"), 1691.9, -3042.7, 286.063, FourCC("nvil"))
    gg_unit_nvl2_0070 = BlzCreateUnitWithSkin(p, FourCC("nvl2"), 2109.6, -3057.2, 260.152, FourCC("nvl2"))
    gg_unit_nvil_0071 = BlzCreateUnitWithSkin(p, FourCC("nvil"), -4946.7, -4773.4, 277.180, FourCC("nvil"))
end

function CreatePlayerBuildings()
end

function CreatePlayerUnits()
    CreateUnitsForPlayer0()
end

function CreateAllUnits()
    CreatePlayerBuildings()
    CreateNeutralHostile()
    CreateNeutralPassive()
    CreatePlayerUnits()
end

function CreateRegions()
    local we
    gg_rct_ironwellenter1 = Rect(12128.0, -16096.0, 18496.0, -9600.0)
    we = AddWeatherEffect(gg_rct_ironwellenter1, FourCC("LRma"))
    EnableWeatherEffect(we, true)
    gg_rct_freydellenter1 = Rect(800.0, -4640.0, 3264.0, -2368.0)
    we = AddWeatherEffect(gg_rct_freydellenter1, FourCC("LRaa"))
    EnableWeatherEffect(we, true)
    gg_rct_rain1 = Rect(-4896.0, -2304.0, 5696.0, 2688.0)
    we = AddWeatherEffect(gg_rct_rain1, FourCC("RAhr"))
    EnableWeatherEffect(we, true)
    gg_rct_rain2 = Rect(-7712.0, -7584.0, -128.0, -2304.0)
    we = AddWeatherEffect(gg_rct_rain2, FourCC("RAhr"))
    EnableWeatherEffect(we, true)
    gg_rct_rain3 = Rect(3296.0, -4704.0, 7104.0, -2304.0)
    we = AddWeatherEffect(gg_rct_rain3, FourCC("RAhr"))
    EnableWeatherEffect(we, true)
    gg_rct_iceenter1 = Rect(-19744.0, -5760.0, -7904.0, 6048.0)
    we = AddWeatherEffect(gg_rct_iceenter1, FourCC("SNhs"))
    EnableWeatherEffect(we, true)
    gg_rct_wolvesenter1 = Rect(480.0, -2272.0, 1536.0, 2688.0)
    gg_rct_wolvesenter2 = Rect(1536.0, -2304.0, 5728.0, -1664.0)
    gg_rct_forestenter1 = Rect(-1120.0, -9184.0, -96.0, 3136.0)
    gg_rct_forestenter2 = Rect(-7744.0, -7584.0, -6720.0, -2528.0)
end

function CreateCameras()
    gg_cam_Camera_001 = CreateCameraSetup()
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ROTATION, 90.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ANGLE_OF_ATTACK, 304.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_TARGET_DISTANCE, 1996.5, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ROLL, 0.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_FARZ, 5000.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_NEARZ, 16.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
    CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
    CameraSetupSetDestPosition(gg_cam_Camera_001, 2116.2, -3115.3, 0.0)
end

function Trig_Untitled_Trigger_001_Actions()
end

function InitTrig_Untitled_Trigger_001()
    gg_trg_Untitled_Trigger_001 = CreateTrigger()
    TriggerRegisterUnitEvent(gg_trg_Untitled_Trigger_001, gg_unit_nvil_0071, EVENT_UNIT_DEATH)
    TriggerRegisterUnitEvent(gg_trg_Untitled_Trigger_001, gg_unit_nvl2_0070, EVENT_UNIT_DEATH)
    TriggerRegisterUnitEvent(gg_trg_Untitled_Trigger_001, gg_unit_nvil_0069, EVENT_UNIT_DEATH)
    TriggerRegisterUnitEvent(gg_trg_Untitled_Trigger_001, gg_unit_nemi_0014, EVENT_UNIT_DEATH)
    TriggerAddAction(gg_trg_Untitled_Trigger_001, Trig_Untitled_Trigger_001_Actions)
end

function InitCustomTriggers()
    InitTrig_Untitled_Trigger_001()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(2), false)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(3), false)
    SetPlayerController(Player(3), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(4), 4)
    ForcePlayerStartLocation(Player(4), 4)
    SetPlayerColor(Player(4), ConvertPlayerColor(4))
    SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(4), false)
    SetPlayerController(Player(4), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(5), 5)
    ForcePlayerStartLocation(Player(5), 5)
    SetPlayerColor(Player(5), ConvertPlayerColor(5))
    SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(5), false)
    SetPlayerController(Player(5), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(6), 6)
    ForcePlayerStartLocation(Player(6), 6)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(6), false)
    SetPlayerController(Player(6), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(7), 7)
    ForcePlayerStartLocation(Player(7), 7)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(7), false)
    SetPlayerController(Player(7), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(8), 8)
    ForcePlayerStartLocation(Player(8), 8)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(8), false)
    SetPlayerController(Player(8), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(9), 9)
    ForcePlayerStartLocation(Player(9), 9)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(9), false)
    SetPlayerController(Player(9), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(10), 10)
    ForcePlayerStartLocation(Player(10), 10)
    SetPlayerColor(Player(10), ConvertPlayerColor(10))
    SetPlayerRacePreference(Player(10), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(10), false)
    SetPlayerController(Player(10), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerTeam(Player(1), 0)
    SetPlayerTeam(Player(2), 0)
    SetPlayerTeam(Player(3), 0)
    SetPlayerTeam(Player(4), 0)
    SetPlayerTeam(Player(5), 0)
    SetPlayerTeam(Player(6), 0)
    SetPlayerTeam(Player(7), 0)
    SetPlayerTeam(Player(8), 0)
    SetPlayerTeam(Player(9), 0)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(8), true)
    SetPlayerTeam(Player(10), 1)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 1)
    SetStartLocPrio(0, 0, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 3)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(1, 1, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 2, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(2, 1)
    SetStartLocPrio(2, 0, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(3, 3)
    SetStartLocPrio(3, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 2, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 1)
    SetStartLocPrio(4, 0, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 1)
    SetStartLocPrio(5, 0, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(6, 3)
    SetStartLocPrio(6, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(6, 1, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(6, 2, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 1)
    SetStartLocPrio(7, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(8, 1)
    SetStartLocPrio(8, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(9, 6)
    SetStartLocPrio(9, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 3, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 4, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 5, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(10, 8)
    SetStartLocPrio(10, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 2, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 3, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 4, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 5, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 6, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 7, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(10, 8)
    SetEnemyStartLocPrio(10, 0, 0, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 1, 1, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 2, 2, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 3, 3, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 4, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 5, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 6, 6, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 7, 7, MAP_LOC_PRIO_LOW)
end

function main()
    SetCameraBounds(-30208.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -29696.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 31232.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 31744.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -30208.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 31744.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 31232.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -29696.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("LordaeronSummerDay")
    SetAmbientNightSound("LordaeronSummerNight")
    SetMapMusic("Music", true, 0)
    CreateRegions()
    CreateCameras()
    CreateAllUnits()
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
end

function config()
    SetMapName("TRIGSTR_003")
    SetMapDescription("TRIGSTR_005")
    SetPlayers(11)
    SetTeams(11)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, -5824.0, -704.0)
    DefineStartLocation(1, 29248.0, -13568.0)
    DefineStartLocation(2, -11648.0, 14272.0)
    DefineStartLocation(3, -20032.0, 11008.0)
    DefineStartLocation(4, 3712.0, -15232.0)
    DefineStartLocation(5, -26368.0, 7360.0)
    DefineStartLocation(6, -23936.0, -6912.0)
    DefineStartLocation(7, -1024.0, -5696.0)
    DefineStartLocation(8, -12480.0, 14528.0)
    DefineStartLocation(9, 14528.0, 28928.0)
    DefineStartLocation(10, 28288.0, 12480.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

