local hero = require('src/hero.lua')
local keyboard = require('src/keyboard.lua')
local mouse = require('src/mouse.lua')
local projectile = require('src/projectile.lua')
local cleanup = require('src/cleanup.lua')
local uiMain = require('src/ui/main.lua')
local leaver = require('src/leaver.lua')
local casttime = require('src/casttime.lua')
local buffloop = require('src/buffloop.lua')
local target = require('src/target.lua')
local damage = require('src/damage.lua')
local party = require('src/party.lua')
local threat = require('src/threat.lua')
local camera = require('src/camera.lua')
local spawnpoint = require('src/spawnpoint.lua')
local spell = require('src/spell.lua')
local buffmanager = require('src/buffs/buffmanager.lua')
local cooldowns = require('src/spells/cooldowns.lua')
local backpack = require('src/items/backpack.lua')
local equipment = require('src/items/equipment.lua')
local itemmanager = require('src/items/itemmanager.lua')

-- TODO create a boss manager
local turtle = require('src/bosses/turtle.lua')

local debug = require('src/debug.lua')

local mainInit = function()
    hero.init()
    keyboard.init()
    mouse.init()
    projectile.init()
    cleanup.init()
    uiMain.init()
    leaver.init()
    casttime.init()
    buffloop.init()
    target.init()
    damage.init()
    party.init()
    print('1')
    threat.init()
    print('2')
    camera.init()
    print('3')
    spawnpoint.init()
    print('4')
    spell.init()
    print('5')
    buffmanager.init()
    print('6')
    cooldowns.init()
    print('7')
    backpack.init()
    print('8')
    equipment.init()
    print('9')
    itemmanager.init()

    print('?????')

    turtle.init()

    print('turtles fukd')
    -- TODO remove for release
    debug.init()
end

TimerStart(CreateTimer(), 0.0, false, mainInit)
